# Generated by Django 4.0.2 on 2022-04-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_anime_category_anime_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='episode_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='trail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
