# Generated by Django 4.0.2 on 2022-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_anime_episode_numbers_anime_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
