# Generated by Django 4.0.2 on 2022-04-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_anime_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epnumber', models.IntegerField(default=0)),
                ('epurl', models.URLField(blank=True, null=True)),
                ('epanmname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.anime')),
            ],
        ),
    ]
