# Generated by Django 4.0.2 on 2022-04-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='epslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
