# Generated by Django 4.0.2 on 2022-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_episodes_epslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
