# Generated by Django 4.0.2 on 2022-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_anime_rating_anime_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
