# Generated by Django 4.0.2 on 2022-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_anime_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='epdlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
