# Generated by Django 4.0.2 on 2022-04-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_episodes_epdlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='trail',
            new_name='trailer',
        ),
    ]
