# Generated by Django 4.0.2 on 2022-05-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_anime_category_ar_category_catname_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
