# Generated by Django 4.0.2 on 2022-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_anime_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='epslug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
