# Generated by Django 4.0.2 on 2022-11-17 15:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_anime_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='epimage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
