# Generated by Django 4.0.2 on 2022-11-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_episodes_epimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='epanmtitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
